import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("exposes gesture settings and a hands-free capture entry point", () => {
  const html = fs.readFileSync(path.join(projectRoot, "index.html"), "utf8");
  assert.match(html, /id="pinch-toggle"/);
  assert.match(html, /id="pinch-category-controls"/);
  assert.match(html, /id="capture-button"/);
  assert.match(html, /id="mode-toggle-button"/);
  assert.match(html, /data-mode-toggle/);
  assert.match(html, /id="capture-countdown"/);
  assert.match(html, /id="loading-meter"/);
  assert.match(html, /id="loading-progress"/);
  assert.match(html, /id="loading-progress-bar"/);
  assert.match(html, /id="loading-progress-value"/);
  assert.match(html, /id="help-button"/);
  assert.match(html, /id="help-dialog"/);
  assert.match(html, /id="fullscreen-button"/);
  assert.match(html, /id="fullscreen-label"/);
  assert.match(html, /class="fullscreen-icon"/);
  assert.doesNotMatch(html, /id="sound-button"/);
  assert.doesNotMatch(html, /id="sound-icon"/);
  assert.doesNotMatch(html, /id="sound-label"/);
  assert.match(html, /id="locale-buttons"/);
  assert.ok(html.indexOf('class="stage-card"') < html.indexOf('class="control-actions stage-actions"'));
  assert.ok(html.indexOf('class="control-actions stage-actions"') < html.indexOf('class="controls"'));
  assert.doesNotMatch(html, /rel="preload"[^>]+as="audio"/);
  assert.doesNotMatch(html, /id="locale-select"/);
  assert.doesNotMatch(html, /id="mode-chip"/);
  assert.doesNotMatch(html, /class="gesture-hint"/);
  assert.doesNotMatch(html, /class="footer-note"/);
  assert.doesNotMatch(html, /id="retry-camera-button"/);
  assert.doesNotMatch(html, /data-i18n="controls\.demo"/);
  assert.doesNotMatch(html, /data-i18n="controls\.camera"/);
  assert.doesNotMatch(html, /手动选择/);
  assert.doesNotMatch(html, /<script[^>]+three\/v97\/three\.min\.js/);
  assert.doesNotMatch(html, /<script[^>]+jeelizFaceFilter/);
});

test("exposes tokenized theme skins with responsive CSS units", () => {
  const html = fs.readFileSync(path.join(projectRoot, "index.html"), "utf8");
  const css = fs.readFileSync(path.join(projectRoot, "styles.css"), "utf8");
  assert.match(html, /data-theme="base"/);
  assert.match(css, /html\[data-theme="fun-mask"\]/);
  assert.match(css, /html\[data-theme="face-change"\]/);
  assert.match(css, /assets\/themes\/fun-mask-cartoon\.png/);
  assert.match(css, /assets\/themes\/face-change-opera\.png/);
  assert.match(css, /clamp\(/);
  assert.match(css, /rem/);
  assert.match(css, /stage-status\.loading/);
  assert.match(css, /@media\s*\(min-width:\s*56rem\)/);
  assert.match(css, /grid-template-areas/);
  assert.match(css, /stage-actions/);
  assert.match(css, /is-fullscreen/);
  assert.match(css, /\.app-shell[\s\S]*overflow:\s*hidden/);
  assert.match(css, /overscroll-behavior:\s*contain/);
  assert.doesNotMatch(css, /sound-button|sound-icon/);
  assert.doesNotMatch(css, /\.controls\s*>\s*\.control-actions[\s\S]*order:\s*-1/);
  assert.match(css, /\.stage-actions[\s\S]*display:\s*flex/);
  assert.match(css, /\.stage-actions[\s\S]*width:\s*fit-content/);
  assert.match(css, /\.stage-actions[\s\S]*max-width:\s*100%/);
  assert.match(css, /\.stage-actions[\s\S]*justify-self:\s*start/);
  assert.match(css, /\.stage-actions[\s\S]*max-height:\s*[^;]+/);
  assert.doesNotMatch(css, /\.stage-actions[\s\S]*border-top:\s*[^;]+/);
  assert.match(css, /@media\s*\(min-width:\s*56rem\)[\s\S]*\.controls[\s\S]*overflow-y:\s*hidden/);
  assert.match(css, /@media\s*\(min-width:\s*56rem\)[\s\S]*\.effect-picker[\s\S]*overflow-y:\s*auto/);
  assert.match(css, /@media\s*\(min-width:\s*56rem\)[\s\S]*\.control-actions[\s\S]*flex-shrink:\s*0/);
  assert.match(css, /@media\s*\(max-width:\s*43\.75rem\)[\s\S]*\.controls[\s\S]*overflow:\s*visible/);
  assert.match(css, /@media\s*\(max-width:\s*43\.75rem\)[\s\S]*\.stage-actions[\s\S]*margin-inline:\s*clamp\(/);
  assert.match(css, /@media\s*\(max-width:\s*43\.75rem\)[\s\S]*\.stage-actions[\s\S]*width:\s*calc\(100%\s*-\s*clamp\(/);
  assert.doesNotMatch(css, /max-height:\s*76vh/);
  assert.doesNotMatch(css, /px/);
});

test("schedules the expensive Canny frame work outside the paint loop", () => {
  const source = fs.readFileSync(path.join(projectRoot, "main.js"), "utf8");
  assert.match(source, /cannyFrameBusy/);
  assert.match(source, /scheduleCannyRefresh/);
  assert.match(source, /CANNY_REFRESH_MS = 1000/);
  assert.match(source, /window\.setTimeout/);
  assert.match(source, /new Worker\("\.\/src\/canny-worker\.js/);
  assert.match(source, /postMessage\(/);
  assert.match(source, /cannyFrameReady &&/);
  assert.match(source, /getCaptureSize\(/);
  assert.match(source, /renderCaptureFrame\(/);
  assert.match(source, /requestFullscreen\(/);
  assert.match(source, /exitFullscreen\(/);
  assert.match(source, /addEventListener\("fullscreenchange"/);
  assert.doesNotMatch(source, /createSoundPlayer|soundPlayer|playSound|AudioContext/);
  assert.doesNotMatch(source, /addEventListener\("pointerdown"/);
});
